service: default
runtime: custom
env: flex

#entrypoint: gunicorn -b :$PORT main:app
entrypoint: gunicorn -b 0.0.0.0:8080 main:server

#env_variables:
#  KAGGLE_USERNAME: "akiman85"
#  KAGGLE_KEY: "95f393a1d2bd0d64736af7df42d0cc86"
  
runtime_config:
  python_version: 3.9

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 8

